on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to publish readme
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Publish README
        id: hello
        uses: johnkayode/hashnode-pub@v0.1.2
        with:
          title: 'Hello World'
          publication_id: '5fca4625a4865f740d163b18'
          coverImage: 'https://fastly.picsum.photos/id/4/5000/3333.jpg'
          access_token: ${{ secrets.HASHNODE_ACCESS_TOKEN }}
          markdown: 'README.md'

      - name: Get the publication url
        run: echo "The Publish url was ${{ steps.hello.outputs.url }}"